CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(320) UNIQUE,
    image_url TEXT
);
CREATE TABLE IF NOT EXISTS user_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    author_id BIGINT REFERENCES users(id),
    json_content JSONB NOT NULL,
    html_content TEXT NOT NULL,
);
CREATE TABLE IF NOT EXISTS user_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment TEXT,
    user_id BIGINT REFERENCES users(id),
    posts_id BIGINT REFERENCES user_posts(id),
    parent_comment_id BIGINT REFERENCES user_comments(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS users_saved_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    posts_id BIGINT REFERENCES user_posts(id),
    UNIQUE (user_id, posts_id)
);
CREATE TABLE IF NOT EXISTS users_post_like (
    user_id BIGINT REFERENCES users(id),
    posts_id BIGINT REFERENCES user_posts(id),
    claps INT,
    PRIMARY KEY (user_id, posts_id)
);